### ISSUE TITLE
Overblocking of nimiq.com

### ISSUE THREAD

**Issue by mar-v-in** [hoshsadiq/adblock-nocoin-list#343]
Since commit cf1f4934edc9bba31c13608d622d478ff6a16107, this list contains the nimiq.com domain. Blocking access to nimiq.com or cdn.nimiq.com will block web apps that make use of the nimiq network, a decentralized application network layer.

According to the description of cf1f4934edc9bba31c13608d622d478ff6a16107, it should block mining on onvid.pw/hdvid.tv. Maybe there is a different way to block the mining on those sites without blocking the whole nimiq network.

**Comment by hoshsadiq** [comment]
If you can provide all the domains your miner runs on, we may be able to add those to the list.

**Comment by hoshsadiq** [comment]
I love this! I don't think you have bought enough domains to prevent your miner being blocked. This is the kind of BS that makes people use lists like this. You should be ashamed of yourself. Quite frankly this kind of behaviour makes me want to block everything related to your nimiq network.

Anyway, I've added all the domains I've found to this list. I'm still happy to take nimiq off the black list providing you can provide a honest full list of all the domains you guys use that your miner connects to.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/600045/50568866-92072f80-0d50-11e9-9a68-9e7b7a80b686.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/600045/50568972-16f34880-0d53-11e9-8f42-1d183cad447b.png">

**Comment by hoshsadiq** [comment]
This isn't about onvid/hdvid. This list exists to block mining. The additional domains I've added are what I thought, to the best of my knowledge, were mining domains.

I understand it's a decentralised network, but the majority of domains that I found, on first impression, seem to be owned by the nimiq network. 

I will take out the main domains and leave the domain that does the mining.

**Comment by niwot** [comment]
Hi, today I have seen in my nextdns.io registry, the following list of domains, some blocked and some not. I have not entered any weird websites, I was looking for pictures of engineering stuff, in google images, for work issues. I don't have the history from my browser, and can't see from which particular link these domains were called from.

I understand that all the domains could have to do with cryptojacking because all those domains have been called from some "normal" website that I have entered (I have not entered any nimiq domain that I remember). But I have hardly any information on these issues, and I pass here the information, in case it would be useful.

I see that the domains nimiq.community; nimiq.icemining.ca; nimiq.surf; seed.nimiq.jp; seed.nimiqchina.com are not blocked by this list, neither is node.nimiq.watch, and perhaps you can evaluate if there are indications or reasons to include them.

Thanks in advance.

This is the list of domains that I have detected browsing today (all domains are registered within 10 minutes, I think it is some browser tab that I left open that time):

domain	status	reasons
nimiq.community		
nimiq.icemining.ca		
nimiq.surf		
node.nimiq.watch	blocked	cryptojacking
seed.nimiq.jp		
seed.nimiqchina.com		
seed.nimiqpool.com	blocked	cryptojacking,blocklist:oisd
seed-1.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-10.nimiq.network	blocked	cryptojacking,blocklist:oisd
seed-11.nimiq.network	blocked	cryptojacking,blocklist:oisd
seed-12.nimiq.network	blocked	cryptojacking,blocklist:oisd
seed-13.nimiq-network.com	blocked	cryptojacking,blocklist:oisd
seed-14.nimiq-network.com	blocked	cryptojacking,blocklist:oisd
seed-15.nimiq-network.com	blocked	cryptojacking,blocklist:oisd
seed-16.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-17.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-18.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-19.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-2.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-20.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-3.nimiq.com	blocked	cryptojacking,blocklist:oisd
seed-4.nimiq-network.com	blocked	cryptojacking,blocklist:oisd
seed-5.nimiq-network.com	blocked	cryptojacking,blocklist:oisd
seed-6.nimiq-network.com	blocked	cryptojacking,blocklist:oisd
seed-7.nimiq.network	blocked	cryptojacking,blocklist:oisd
seed-8.nimiq.network	blocked	cryptojacking,blocklist:oisd
seed-9.nimiq.network	blocked	cryptojacking,blocklist:oisd
