### ISSUE TITLE
No updates since 3/10/2022.

### ISSUE THREAD

**Issue by antdude** [hoshsadiq/adblock-nocoin-list#437]
Is this list dead?

**Comment by hoshsadiq** [comment]
I wouldn't say that, however, updates have mostly stopped because we've had no reports of new domains popping up (and I personally haven't seen any either). This, combined with other lists that include JS mining websites, has caused this list to slow down a bit.

For reference, [CoinBlockerLists](https://gitlab.com/ZeroDot1/CoinBlockerLists) has also had fewer updates lately.

I'm more than happy to investigate and add additional JS mining websites if you find one!

**Comment by antdude** [comment]
Thank you for the quick answer. :)
