### ISSUE TITLE
Quicknode RPC Endpoints Websocket calls are getting blocked

### ISSUE THREAD

**Issue by quick-pawiromitchel** [hoshsadiq/adblock-nocoin-list#439]
hey team!

I have an endpoint at Quicknode and AdBlock is blocking websocket calls, the endpoint url is like this
`wss://<random-name>.quiknode.pro/<token>/`

![CleanShot 2022-08-09 at 08 40 10](https://user-images.githubusercontent.com/103942361/183638526-62bca21e-4480-4500-a451-565e379fa16f.png)

Are you able to add this domain to the whitelist?

**Comment by alyavasilyeva** [comment]
Since we've added Quicknode as an rpc provider to our website, some users started complaining that data does not load. 
It turned out that they've been using AdBlock with `Cryptocurrency (Bitcoin) Mining Protection List` filter on, so Quicknode websocket calls failed 🙁 It would be great if Quicknode could be whitelisted
