### ISSUE TITLE
New Coinhive-domain

### ISSUE THREAD

**Issue by svaraej** [hoshsadiq/adblock-nocoin-list#52]
Hi!

authedmine.com seems to be the domain that Coinhive's scripts currently are loaded from. Source: https://coinhive.com/documentation/miner

Best regards,
svaraej

**Comment by hoshsadiq** [comment]
Thanks for the report. I feel that this is the right way of cryptomining. Opt-in with a way to opt-out at any time. I will leave this open and contact Coinhive to see what guarantee they are able to give the users that no mining is started without consent. Looking at their docs, it seems they have a sane thing going that works for webmasters and users as opposed to what was happening previously.

**Comment by hoshsadiq** [comment]
@SMed79 what do you think?

**Comment by Leseratte10** [comment]
I'm not involved with Coinhive but I also think that these two commits should be reverted. 

AuthedMine provides javascript files with a monero miner, but each and every script hosted on that domain only starts running when the user actively allows it to. If you visit the authedmine webpage (https://authedmine.com/ ), they explain how this works - the scripts load an opt-in dialog from their web page (which can **not** be altered by the web page embedding this), and their server sends the client an authentication token. When the script starts running and requests "work" from the server, it checks if the token is valid. So even if someone would somehow "on the fly" modifiy the scripts from authedmine, the script would still not mine without permission - the server would not give the script things to work on because the permission page hasn't been accepted. This is all server-side and can not be changed from within the client. 

Pages like authedmine.com need to be removed from any filter list. I understand "NoCoin"-lists for malicious domains mining without consent, but if done correctly (like authedmine), it can be a valid alternative to advertisement.

**Comment by svaraej** [comment]
Hi!

After reading the  comments and a bit of the documentation, I've decided to support the idea of not adding authedmine.com to the filter list. I wrongfully assumed that Coinhive's only change was the domain, I stand corrected!

Thank you @hoshsadiq and @Leseratte10 for both quick and insightful replies!

**Comment by hoshsadiq** [comment]
I have been in touch with Coinhive. I will be keeping authedmine off the list, but will keep an eye on authedmine.

**Comment by SMed79** [comment]
@hoshsadiq 
> what do you think?

The content is blocked and mining is forced!
Do you think it is reasonable?

**Comment by Leseratte10** [comment]
Mining is forced? What do you mean by that? The scripts on authedmine do not automatically force-run, they ask for permission and only run if the user allows it ...

**Comment by SMed79** [comment]
authedmine captcha is just replacing an anti-adblock (no access to the contents without mining).

e.g. `http://mylink.st/ZQFTnbU`

The normal users are thinking they are solving a normal CAPTCHA which is is untrue.

**Comment by Leseratte10** [comment]
And how does blocking that help preventing "anti-adblock"? Blocking it would completely lock the user out of the content (unless they disable the adblocker temporarily). That would just mean that pages like this add a hint iike "disable your adblock to continue". 

What does this achieve? If an user doesn't know what "proof-of-work" is (which is written on the captcha element), how does an adblocker help that user? This is a captcha-like variant. If a user visits this page, he wants to visit the link hidden behind this page. If this is not blocked, he clicks the box, reads the explaination, if he wants to, and then gets access to the link. 
If this is blocked by the adblocker, you just add "user disables his adblocker" to the list. This is not a thing grabbing user data or spamming them with random ads. 
This is a thing the user actively wants to run - even if he doesn't understand, what it is. And because the user actively wants to run it, he *will* run it, even if that means disabling his adblock. 

Please don't block these things again - I understand blocking coinhive, but not authedmine. The operators of Coin Hive did a lot to make this safe and useable - new domain which disables auto-run, explaination links visible, server tokens to prevent modified scripts from autorunning, etc. 

"normal users" would just be more confused with an explaination like "hey we use your CPU". More advanced users can click the link to find out. Normal users just want to get that link and go away.
